### ISSUE TITLE
prometheus配置支持 https

### ISSUE THREAD

**Issue by ushell** [hyperf/metric#3]
metrics配置中如果采用`PUSH_MODE`方式（prometheus pushgateway），`PROMETHEUS_PUSH_HOST`仅支持`http`方式

具体代码: https://github.com/hyperf/metric/blob/master/src/Adapter/Prometheus/MetricFactory.php#L161

建议代码:
```php
if (! Str::contains($address, ['https://', 'http://']))
{
    $address = 'http://' . $address;
}
```

**Comment by huangzhhui** [comment]
可以提个 PR 过来优化一下

**Comment by ushell** [comment]
PR: #4 

项目貌似readonly, 不能合并PR?

**Comment by limingxinleo** [comment]
代码提交到hyperf/hyperf仓库
