### ISSUE TITLE
Unable to download version error

### ISSUE THREAD

**Issue by cexll** [hyperf/metric#5]
![image](https://user-images.githubusercontent.com/26520956/108470342-cdfd0600-72c4-11eb-8c1a-2ebf1c7a23fc.png)

**Comment by limingxinleo** [comment]
https://www.zhihu.com/zvideo/1333548431042433024

**Comment by cexll** [comment]
不对, 是 `endclothing/prometheus_client_php 1.0` 需要依赖 guzzle6 
但是我本地锁了guzzle7.2了
本地使用 hyperf/guzzle

**Comment by limingxinleo** [comment]
看文档，有讲

**Comment by limingxinleo** [comment]
![image](https://user-images.githubusercontent.com/16648551/108582279-22f45700-736d-11eb-98f5-5cdf60fa19b3.png)

**Comment by cexll** [comment]
了解, 我直接-W 给他降级了 其他组件没有强制依赖7
